package com.moneytracker.app.ui.theme

import androidx.compose.ui.graphics.Color

// ─── Material 3 Dark Color Scheme ───────────────────────────────────
val md_theme_dark_primary = Color(0xFFFF9800)           // Stronger Orange
val md_theme_dark_onPrimary = Color(0xFF4E2600)
val md_theme_dark_primaryContainer = Color(0xFF6F3800)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC2)
val md_theme_dark_secondary = Color(0xFF2196F3)          // Clear Blue
val md_theme_dark_onSecondary = Color(0xFF003258)
val md_theme_dark_secondaryContainer = Color(0xFF00497D)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE5FF)
val md_theme_dark_tertiary = Color(0xFF4CAF50)           // Clear Green
val md_theme_dark_onTertiary = Color(0xFF003A02)
val md_theme_dark_tertiaryContainer = Color(0xFF005304)
val md_theme_dark_onTertiaryContainer = Color(0xFFA5F5A0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFECECEC)
val md_theme_dark_surface = Color(0xFF121212)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF45464A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFBCC2)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1E1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF8B5000)
val md_theme_dark_surfaceTint = Color(0xFFFFB74D)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
val md_theme_dark_scrim = Color(0xFF000000)

// ─── Material 3 Light Color Scheme ──────────────────────────────────
val md_theme_light_primary = Color(0xFFFF9800)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE0B2)
val md_theme_light_onPrimaryContainer = Color(0xFF2D1600)
val md_theme_light_secondary = Color(0xFF1565C0)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D36)
val md_theme_light_tertiary = Color(0xFF2E7D32)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF7BFC6E)
val md_theme_light_onTertiaryContainer = Color(0xFF002201)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE0E0E0)
val md_theme_light_onSurfaceVariant = Color(0xFF424242)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFFFB74D)
val md_theme_light_surfaceTint = Color(0xFF8B5000)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

// ─── Brand / Semantic Colors (backward-compatible aliases) ──────────
val DarkBackground = Color(0xFF1E1E1E)
val DarkSurface = Color(0xFF2D2D2D)
val DarkSurfaceVariant = Color(0xFF383838)
val DarkOnSurface = Color(0xFFE0E0E0)
val DarkOnSurfaceVariant = Color(0xFF9E9E9E)

val ExpenseRed = Color(0xFFF44336)
val IncomeGreen = Color(0xFF4CAF50)
val TransferBlue = Color(0xFF2196F3)
val AccentOrange = Color(0xFFFF9800)
val AccentPurple = Color(0xFF9C27B0)

// Category Colors
val CategoryFood = Color(0xFFFF5722)
val CategoryTransport = Color(0xFF2196F3)
val CategoryShopping = Color(0xFF9C27B0)
val CategoryEntertainment = Color(0xFFE91E63)
val CategoryHealth = Color(0xFF4CAF50)
val CategoryEducation = Color(0xFF3F51B5)
val CategoryBills = Color(0xFFFF9800)
val CategoryRent = Color(0xFF795548)
val CategoryBike = Color(0xFF607D8B)
val CategoryCats = Color(0xFFFFEB3B)

// Surface levels
val CardBackground = Color(0xFF2D2D2D)
val CardBackgroundElevated = Color(0xFF353535)
val DividerColor = Color(0xFF404040)

// Text Colors
val TextPrimary = Color(0xFFFFFFFF)
val TextSecondary = Color(0xFFB0B0B0)
val TextTertiary = Color(0xFF757575)
